### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by Ali00** [ravel-net/REU-access-control#1]
Hi,

Could you please advise me in how to resolve the issue that I face while running the following code:

$ sudo python ./ravel/ravel.py --custom=./ravel/topo/sla_topo.py --topo=mytopo --onlydb
I attached the snapshot of the error message.

-- I also did exactly what the instruction says
1- I copied the acl.sql and acl.py files into the ~/ravel/apps
2- I copied sla_topo.py into the ~/ravel/topo folder 
3- I copied the  acl_demo.sh file into the VM's home directory (as shown in the screen-shot)

![issue 1](https://cloud.githubusercontent.com/assets/12594727/20276146/00e1c99c-aa93-11e6-8d27-c8ac334389ef.png)

Thanks,

**Comment by croft** [comment]
The line "<!DOCTYPE html>" isn't part of sla_topo.py.  Can you check that you didn't accidentally download the HTML source code for the sla_topo.py preview file?  Or, try re-downloading the file from here: https://raw.githubusercontent.com/ravel-net/REU-access-control/master/sla_topo.py.

**Comment by Ali00** [comment]
Oh yes that was my fault :-) 

Many thanks,
